// resources/js/components/RichTextEditor.tsx
import React, { useEffect } from 'react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {
    Bold,
    Heading2,
    Heading3,
    Italic,
    List,
    ListOrdered,
    Minus,
    Redo2,
    Strikethrough,
    TextQuote,
    Undo2,
} from 'lucide-react';

interface RichTextEditorProps {
    value?: string;
    modelValue?: string;
    onChange?: (value: string) => void;
    placeholder?: string;
    invalid?: boolean;
}

export default function RichTextEditor({
    value = '',
    modelValue = '',
    onChange,
    placeholder = '',
    invalid = false,
}: RichTextEditorProps) {
    const content = value || modelValue || '';

    const editor = useEditor({
        extensions: [StarterKit],
        content,
        editorProps: {
            attributes: {
                class: 'rich-text min-h-40 px-3 py-2 text-sm focus:outline-none',
            },
        },
        onUpdate: ({ editor }) => {
            onChange?.(editor.isEmpty ? '' : editor.getHTML());
        },
    });

    useEffect(() => {
        if (editor && content !== editor.getHTML()) {
            editor.commands.setContent(content || '');
        }
    }, [content, editor]);

    if (!editor) {
        return null;
    }

    return (
        <div
            className={`rounded-lg border bg-white dark:bg-slate-900 ${
                invalid
                    ? 'border-rose-400 dark:border-rose-700'
                    : 'border-slate-200 dark:border-slate-700'
            }`}
        >
            <div className="flex flex-wrap items-center gap-1 border-b border-slate-200 p-1.5 dark:border-slate-800">
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleBold().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('bold')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Bold"
                >
                    <Bold className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleItalic().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('italic')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Italic"
                >
                    <Italic className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleStrike().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('strike')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Strikethrough"
                >
                    <Strikethrough className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('heading', { level: 2 })
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Heading 2"
                >
                    <Heading2 className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleHeading({ level: 3 }).run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('heading', { level: 3 })
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Heading 3"
                >
                    <Heading3 className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleBulletList().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('bulletList')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Bullet List"
                >
                    <List className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleOrderedList().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('orderedList')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Ordered List"
                >
                    <ListOrdered className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().toggleBlockquote().run()}
                    className={`rounded p-1.5 transition ${
                        editor.isActive('blockquote')
                            ? 'bg-slate-200 text-slate-900 dark:bg-slate-700 dark:text-white'
                            : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'
                    }`}
                    title="Blockquote"
                >
                    <TextQuote className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().setHorizontalRule().run()}
                    className="rounded p-1.5 text-slate-600 transition hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
                    title="Horizontal Line"
                >
                    <Minus className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().undo().run()}
                    disabled={!editor.can().undo()}
                    className="rounded p-1.5 text-slate-600 transition hover:bg-slate-100 disabled:opacity-30 dark:text-slate-400 dark:hover:bg-slate-800"
                    title="Undo"
                >
                    <Undo2 className="h-4 w-4" />
                </button>
                <button
                    type="button"
                    onClick={() => editor.chain().focus().redo().run()}
                    disabled={!editor.can().redo()}
                    className="rounded p-1.5 text-slate-600 transition hover:bg-slate-100 disabled:opacity-30 dark:text-slate-400 dark:hover:bg-slate-800"
                    title="Redo"
                >
                    <Redo2 className="h-4 w-4" />
                </button>
            </div>
            <EditorContent editor={editor} />
        </div>
    );
}

// resources/js/components/RichTextEditor.vue
<script setup lang="ts">
import { watch, type FunctionalComponent } from 'vue'
import { EditorContent, useEditor } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import {
    Bold,
    Heading2,
    Heading3,
    Italic,
    List,
    ListOrdered,
    Minus,
    Redo2,
    Strikethrough,
    TextQuote,
    Underline,
    Undo2,
} from '@lucide/vue'

const props = withDefaults(
    defineProps<{
        modelValue: string
        placeholder?: string
        invalid?: boolean
    }>(),
    {
        placeholder: '',
        invalid: false,
    },
)

const emit = defineEmits<{
    (e: 'update:modelValue', value: string): void
}>()

const editor = useEditor({
    content: props.modelValue,
    extensions: [StarterKit],
    editorProps: {
        attributes: {
            class: 'rich-text min-h-40 px-3 py-2 text-sm focus:outline-none',
        },
    },
    onUpdate: ({ editor }) => {
        emit('update:modelValue', editor.isEmpty ? '' : editor.getHTML())
    },
})

watch(
    () => props.modelValue,
    (value) => {
        if (editor.value && value !== editor.value.getHTML()) {
            editor.value.commands.setContent(value || '')
        }
    },
)

interface ToolButton {
    icon: FunctionalComponent
    title: string
    action: () => void
    isActive?: () => boolean
    isDisabled?: () => boolean
}

const buttons: ToolButton[] = [
    {
        icon: Bold,
        title: 'Bold',
        action: () => editor.value?.chain().focus().toggleBold().run(),
        isActive: () => editor.value?.isActive('bold') ?? false,
    },
    {
        icon: Italic,
        title: 'Italic',
        action: () => editor.value?.chain().focus().toggleItalic().run(),
        isActive: () => editor.value?.isActive('italic') ?? false,
    },
    {
        icon: Underline,
        title: 'Underline',
        action: () => editor.value?.chain().focus().toggleUnderline().run(),
        isActive: () => editor.value?.isActive('underline') ?? false,
    },
    {
        icon: Strikethrough,
        title: 'Strikethrough',
        action: () => editor.value?.chain().focus().toggleStrike().run(),
        isActive: () => editor.value?.isActive('strike') ?? false,
    },
    {
        icon: Heading2,
        title: 'Heading',
        action: () =>
            editor.value?.chain().focus().toggleHeading({ level: 2 }).run(),
        isActive: () => editor.value?.isActive('heading', { level: 2 }) ?? false,
    },
    {
        icon: Heading3,
        title: 'Subheading',
        action: () =>
            editor.value?.chain().focus().toggleHeading({ level: 3 }).run(),
        isActive: () => editor.value?.isActive('heading', { level: 3 }) ?? false,
    },
    {
        icon: List,
        title: 'Bullet list',
        action: () => editor.value?.chain().focus().toggleBulletList().run(),
        isActive: () => editor.value?.isActive('bulletList') ?? false,
    },
    {
        icon: ListOrdered,
        title: 'Numbered list',
        action: () => editor.value?.chain().focus().toggleOrderedList().run(),
        isActive: () => editor.value?.isActive('orderedList') ?? false,
    },
    {
        icon: TextQuote,
        title: 'Quote',
        action: () => editor.value?.chain().focus().toggleBlockquote().run(),
        isActive: () => editor.value?.isActive('blockquote') ?? false,
    },
    {
        icon: Minus,
        title: 'Divider',
        action: () => editor.value?.chain().focus().setHorizontalRule().run(),
    },
    {
        icon: Undo2,
        title: 'Undo',
        action: () => editor.value?.chain().focus().undo().run(),
        isDisabled: () => !(editor.value?.can().undo() ?? false),
    },
    {
        icon: Redo2,
        title: 'Redo',
        action: () => editor.value?.chain().focus().redo().run(),
        isDisabled: () => !(editor.value?.can().redo() ?? false),
    },
]
</script>

<template>
    <div
        :class="[
            'mt-1 overflow-hidden rounded-md border bg-white transition focus-within:ring-2 focus-within:ring-accent-500/20 dark:bg-slate-950',
            invalid
                ? 'border-rose-500'
                : 'border-slate-200 focus-within:border-accent-500 dark:border-slate-700',
        ]"
    >
        <div
            class="flex flex-wrap items-center gap-0.5 border-b border-slate-200 bg-slate-50 px-2 py-1.5 dark:border-slate-700 dark:bg-slate-900"
        >
            <button
                v-for="button in buttons"
                :key="button.title"
                type="button"
                :title="button.title"
                :disabled="button.isDisabled?.() ?? false"
                :class="[
                    'inline-flex h-7 w-7 items-center justify-center rounded transition disabled:cursor-not-allowed disabled:opacity-40',
                    button.isActive?.()
                        ? 'bg-accent-600 text-white'
                        : 'text-slate-600 hover:bg-slate-200 dark:text-slate-300 dark:hover:bg-slate-800',
                ]"
                @click="button.action()"
            >
                <component :is="button.icon" class="h-4 w-4" :stroke-width="2" />
            </button>
        </div>

        <EditorContent :editor="editor" />
    </div>
</template>
