// resources/js/pages/Admin/Results/ReportCard.tsx
import { Head } from '@inertiajs/react';
import { useEffect } from 'react';
import DashboardLayout from '@/layouts/DashboardLayout';
import ReportCard, { type Report } from '@/components/ReportCard';
import { useSidebarStack } from '@/composables/useNavStack';
import type { SidebarConfig } from '@/types/sidebar';

interface Props {
    report: Report;
    backHref: string;
    pdfHref: string;
    sidebar: SidebarConfig;
}

export default function ReportCardPage({ report, backHref, pdfHref, sidebar }: Props) {
    const sidebarStack = useSidebarStack();
    useEffect(() => {
        sidebarStack.set(sidebar);
    }, [sidebar]);

    return (
        <DashboardLayout>
            <Head title={`Gradesheet - ${report.student.name_en}`} />
            <ReportCard
                report={report}
                backHref={backHref}
                pdfHref={pdfHref}
            />
        </DashboardLayout>
    );
}

// resources/js/pages/Admin/Results/ReportCard.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import ReportCard, { type Report } from '@/components/ReportCard.vue';
import { useSidebarStack } from '@/composables/useNavStack';
import type { SidebarConfig } from '@/types/sidebar';

defineOptions({ layout: DashboardLayout });

const props = defineProps<{
    report: Report;
    backHref: string;
    pdfHref: string;
    sidebar: SidebarConfig;
}>();

useSidebarStack().set(props.sidebar);
</script>

<template>
    <div>
        <Head :title="`Gradesheet - ${report.student.name_en}`" />
        <ReportCard
            :report="report"
            :back-href="backHref"
            :pdf-href="pdfHref"
        />
    </div>
</template>
