// resources/js/pages/Site/Syllabus.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import PublicLayout from '@/layouts/PublicLayout.vue';
import AppIcon from '@/components/AppIcon.vue';

defineOptions({ layout: PublicLayout });

interface SyllabusItem {
    id: number;
    title: string;
    description: string | null;
    file_url: string | null;
    class_label: string | null;
    session_name: string | null;
}

defineProps<{ syllabuses: SyllabusItem[] }>();
</script>

<template>
    <div>
        <Head title="Syllabus" />

        <section class="bg-[#1e2875] text-[#f7f3e8]">
            <div class="mx-auto max-w-6xl px-4 py-14 sm:px-6 lg:px-8">
                <p class="text-xs font-semibold tracking-[0.25em] text-[#c9a227] uppercase">Academics</p>
                <div class="mt-2 h-px w-16 bg-[#c9a227]" aria-hidden="true"></div>
                <h1 class="mt-5 font-serif text-3xl font-bold sm:text-4xl">Class Syllabus</h1>
            </div>
        </section>

        <section class="mx-auto max-w-5xl px-4 py-14 sm:px-6 lg:px-8">
            <div v-if="syllabuses.length" class="grid gap-6 sm:grid-cols-2">
                <div
                    v-for="item in syllabuses"
                    :key="item.id"
                    class="flex flex-col rounded-lg border border-[#1e2875]/10 bg-white p-6 shadow-sm"
                >
                    <div class="flex items-start justify-between gap-3">
                        <div>
                            <p v-if="item.class_label" class="text-xs font-semibold tracking-widest text-[#c9a227] uppercase">
                                Class {{ item.class_label }}
                            </p>
                            <h2 class="mt-1 font-serif text-lg font-bold text-[#1e2875]">{{ item.title }}</h2>
                            <p v-if="item.session_name" class="mt-0.5 text-xs text-[#1a1a1a]/50">
                                Session {{ item.session_name }}
                            </p>
                        </div>
                        <AppIcon name="book-open" class="h-6 w-6 shrink-0 text-[#1e2875]/40" />
                    </div>

                    <p v-if="item.description" class="mt-3 flex-1 text-sm leading-relaxed text-[#1a1a1a]/70">
                        {{ item.description }}
                    </p>

                    <a
                        v-if="item.file_url"
                        :href="item.file_url"
                        target="_blank"
                        rel="noopener"
                        class="mt-4 inline-flex w-fit items-center gap-2 rounded bg-[#1e2875] px-4 py-2 text-sm font-semibold text-[#f7f3e8] transition-colors hover:bg-[#c9a227] hover:text-[#1a1a1a]"
                    >
                        <AppIcon name="download" class="h-4 w-4" />
                        Download syllabus
                    </a>
                </div>
            </div>
            <p v-else class="rounded-lg border border-dashed border-[#1e2875]/20 p-8 text-center text-sm text-[#1a1a1a]/60">
                Syllabus documents have not been published yet.
            </p>
        </section>
    </div>
</template>

// resources/js/pages/Admin/Syllabus/Index.tsx
import { Head, Link, router, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import DashboardLayout from '@/layouts/DashboardLayout';
import AppIcon from '@/components/AppIcon';
import { useSidebarStack } from '@/composables/useNavStack';
import type { SidebarConfig } from '@/types/sidebar';

interface SyllabusRow {
    id: number;
    title: string;
    description: string | null;
    file_url: string | null;
    class_label: string;
    session_name: string;
}

interface Props {
    sidebar: SidebarConfig;
    syllabuses: {
        data: SyllabusRow[];
        from: number | null;
        to: number | null;
        total: number;
        last_page: number;
        current_page: number;
    };
}

export default function Index({ sidebar, syllabuses }: Props) {
    const sidebarStack = useSidebarStack();
    useEffect(() => {
        sidebarStack.set(sidebar);
    }, [sidebar]);

    const { flash } = usePage<{ flash?: { message?: string } }>().props;
    const [search, setSearch] = useState('');

    const filtered = syllabuses.data.filter((s) => {
        if (!search) return true;
        const q = search.toLowerCase();
        return (
            s.title.toLowerCase().includes(q) ||
            s.class_label.toLowerCase().includes(q) ||
            s.session_name.toLowerCase().includes(q)
        );
    });

    function destroy(id: number) {
        if (confirm('Are you sure you want to delete this syllabus?')) {
            router.delete(`/admin/syllabus/${id}`);
        }
    }

    return (
        <DashboardLayout>
            <Head title="Syllabus" />

            <div className="space-y-6">
                <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                    <div>
                        <p className="text-xs font-semibold tracking-widest text-slate-500 uppercase dark:text-slate-400">
                            Academic
                        </p>
                        <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl dark:text-slate-50">
                            Syllabus
                        </h1>
                        <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
                            Manage class syllabuses and curriculum documents.
                        </p>
                    </div>
                    <Link
                        href="/admin/syllabus/create"
                        className="inline-flex items-center gap-1.5 self-start rounded-md bg-accent-600 px-3 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-accent-700 sm:self-auto"
                    >
                        <AppIcon name="plus" className="h-4 w-4" />
                        Add syllabus
                    </Link>
                </header>

                {flash?.message && (
                    <div className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">
                        {flash.message}
                    </div>
                )}

                <section className="rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                    <div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800">
                        <label className="relative flex flex-1 items-center sm:max-w-xs">
                            <AppIcon
                                name="search"
                                className="pointer-events-none absolute left-3 h-4 w-4 text-slate-400"
                            />
                            <input
                                value={search}
                                onChange={(e) => setSearch(e.target.value)}
                                type="search"
                                placeholder="Search syllabuses…"
                                className="h-9 w-full rounded-md border border-slate-200 bg-white pr-3 pl-9 text-sm text-slate-900 placeholder-slate-400 focus:border-accent-500 focus:ring-2 focus:ring-accent-500/20 focus:outline-none dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:placeholder-slate-500"
                            />
                        </label>
                        <span className="text-xs text-slate-500 dark:text-slate-400">
                            {filtered.length} of {syllabuses.total} syllabuses
                        </span>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800">
                            <thead className="bg-slate-50 text-left text-xs font-semibold tracking-wider text-slate-500 uppercase dark:bg-slate-950/40 dark:text-slate-400">
                                <tr>
                                    <th className="px-4 py-3">Title</th>
                                    <th className="px-4 py-3">Class</th>
                                    <th className="px-4 py-3">Session</th>
                                    <th className="px-4 py-3">File</th>
                                    <th className="px-4 py-3 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                                {filtered.map((syllabus) => (
                                    <tr
                                        key={syllabus.id}
                                        className="text-slate-700 hover:bg-slate-50/60 dark:text-slate-200 dark:hover:bg-slate-800/40"
                                    >
                                        <td className="px-4 py-3">
                                            <p className="font-medium text-slate-900 dark:text-slate-100">
                                                {syllabus.title}
                                            </p>
                                            {syllabus.description && (
                                                <p className="max-w-md truncate text-xs text-slate-500 dark:text-slate-400">
                                                    {syllabus.description}
                                                </p>
                                            )}
                                        </td>
                                        <td className="px-4 py-3">
                                            {syllabus.class_label}
                                        </td>
                                        <td className="px-4 py-3">
                                            {syllabus.session_name}
                                        </td>
                                        <td className="px-4 py-3">
                                            {syllabus.file_url ? (
                                                <a
                                                    href={syllabus.file_url}
                                                    target="_blank"
                                                    rel="noopener"
                                                    className="inline-flex items-center gap-1.5 text-accent-600 hover:underline dark:text-accent-400"
                                                >
                                                    <AppIcon name="download" className="h-4 w-4" />
                                                    View
                                                </a>
                                            ) : (
                                                <span>—</span>
                                            )}
                                        </td>
                                        <td className="px-4 py-3 text-right">
                                            <div className="inline-flex items-center gap-1">
                                                <Link
                                                    href={`/admin/syllabus/${syllabus.id}/edit`}
                                                    className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-500 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-100"
                                                    aria-label="Edit syllabus"
                                                >
                                                    <AppIcon name="pencil" className="h-4 w-4" />
                                                </Link>
                                                <button
                                                    type="button"
                                                    className="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-500 hover:bg-rose-50 hover:text-rose-600 dark:text-slate-400 dark:hover:bg-rose-950/30 dark:hover:text-rose-400"
                                                    aria-label="Delete syllabus"
                                                    onClick={() => destroy(syllabus.id)}
                                                >
                                                    <AppIcon name="trash" className="h-4 w-4" />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                                {filtered.length === 0 && (
                                    <tr>
                                        <td
                                            colSpan={5}
                                            className="px-4 py-12 text-center text-sm text-slate-500 dark:text-slate-400"
                                        >
                                            No syllabuses found.
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </DashboardLayout>
    );
}
